# Generated by Django 5.0.3 on 2024-03-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_test_fx', '0002_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='members',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='members',
            name='surname',
            field=models.CharField(default='default'),
        ),
    ]
