version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - 7890:80
  
  bck_django:
    container_name: bck_django
    build:
      dockerfile: Dockerfile.django
    restart: on-failure
    ports:
      - 8000:8000

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bck_django
      - POSTGRES_PASSWORD=bck_django
      - POSTGRES_DB=db_bck_django
    ports:
      - 5432:5432