FROM python:3.11.4-slim-buster

WORKDIR /usr/backend

# RUN mkdir -p /usr/backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc && \
    apt-get install -y netcat

RUN pip install --upgrade pip

RUN pip install django
RUN pip install gunicorn
RUN pip install psycopg2-binary

COPY backend/. .

# COPY ./script_django.sh .
RUN sed -i 's/\r$//g' /usr/backend/script_django.sh
RUN chmod 777 /usr/backend/script_django.sh

COPY ./test.sh .
RUN sed -i 's/\r$//g' /usr/backend/test.sh
RUN chmod +x /usr/backend/test.sh

RUN sh /usr/backend/test.sh

RUN addgroup --system bck_django && adduser --system --group bck_django
RUN chown -R bck_django:bck_django /usr/backend

USER bck_django

ENTRYPOINT ["/usr/backend/script_django.sh"]